print("Welcome to the tip calculator!")
totalBill = float(input("What was the total bill?..: $"))
tip = float(input("How much tip would you like to give? 10, 12, or 15?"))
numberOfPeople = int(input("How many people to split the bill? "))
amount = (totalBill + (totalBill * (tip / 100))) / (numberOfPeople)
new_amount = round(amount, 2)
print(f"Each person should pay..: ${new_amount}")
